test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("uploads") %>
disk:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: "streamingsoundtracks"
  credentials: <%= ENV["GOOGLE_APPLICATION_CREDENTIALS"] %>
  bucket: "streamingsoundtracks"